language: objective-c
xcode_project: MJExtension.xcodeproj
xcode_scheme: MJExtension

env:
  global:
    - FRAMEWORK_NAME=MJExtension
before_install:
  - gem install xcpretty
  
script:
  - xcodebuild -project $FRAMEWORK_NAME.xcodeproj -scheme $FRAMEWORK_NAME build | xcpretty
  - pod lib lint

  - carthage build --no-skip-current

notifications:
  email: false
